Cjc 350
18F/piipan pull request #2933
Opened 2022-04-04 16:39 UTC by ccaprio97

## What’s changing?

Changing Api name to Bulk API

## Why?

https://e-jira.fns.usda.net/jira-prod/browse/NAC-350 

## This PR has:

- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

## Anything else?

2022-04-04 17:23 UTC, ryangeorgeharvey commented on docs/openapi/bulk-api.yaml
> -  '/upload/{filename}':
Question: Since we are keeping both APIM endpoints for the time-being, should we keep the API document in sync? I don't know the requirements, so unsure if it matters.

2022-04-04 17:29 UTC, ryangeorgeharvey reviewed
todo (blocking): Remove 'docs/openapi/generated/duplicate-participation-api/openapi.yaml' from the commit. I don't see any file that would have generated this change.

todo (blocking): Fix APIM.json formatting

2022-04-04 18:43 UTC, bgfoshay requested changes
Can you verify that some of your changes were intended? It looks like maybe there was a merge issue?

2022-04-04 18:43 UTC, bgfoshay commented on docs/openapi/generated/duplicate-participation-api/openapi.yaml
> +                                      example: 2021-01
Issue: I'm not sure this looks right. Did Krishna's recent changes somehow get undone? I believe this format/example should display the date range format, right?

2022-04-04 18:43 UTC, bgfoshay commented on docs/openapi/generated/duplicate-participation-api/openapi.yaml
> +                                - 2021-05-01/2021-05-31
Question: Did you intend to remove the single quotes?

2022-04-04 18:43 UTC, bgfoshay commented on docs/openapi/generated/duplicate-participation-api/openapi.yaml
> +                                - 2021-05-01/2021-05-31
Question: Same question as above, did you intend to remove the single quotes?

2022-04-04 18:51 UTC, ccaprio97 commented on docs/openapi/bulk-api.yaml
> -  '/upload/{filename}':
@bgfoshay  thoughts?

2022-04-04 18:51 UTC, bgfoshay commented on docs/openapi/generated/duplicate-participation-api/openapi.yaml
> +                                      example: 2021-01
Yes, please go ahead and change them back.

2022-04-04 18:59 UTC, ccaprio97 commented
> todo (blocking): Remove 'docs/openapi/generated/duplicate-participation-api/openapi.yaml' from the commit. I don't see any file that would have generated this change.
> 
> todo (blocking): Fix APIM.json formatting

@ryangeorgeharvey  
I can remove the file if you think its better but I thought that file was always updated when you run the generate docs script because thats the yaml file thats in the generated folder?

as for the APIM.json formatting im not sure whats wrong with it?

2022-04-04 22:07 UTC, ryangeorgeharvey commented
> > todo (blocking): Remove 'docs/openapi/generated/duplicate-participation-api/openapi.yaml' from the commit. I don't see any file that would have generated this change.
> > todo (blocking): Fix APIM.json formatting
> 
> @ryangeorgeharvey I can remove the file if you think its better but I thought that file was always updated when you run the generate docs script because thats the yaml file thats in the generated folder?
> 
> as for the APIM.json formatting im not sure whats wrong with it?

I didn't mean to remove the file entirely, just remove your changes, which is the same thing Bill mentioned and it looks to be fixed.

For apim.json, it is line 281 that needs less indentation.

2022-04-05 15:28 UTC, ccaprio97 reviewed
updated api description on deprecated endpoint

2022-04-05 19:40 UTC, bgfoshay approved these changes

2022-04-06 15:09 UTC, kingcomma commented
@ccaprio97 @bgfoshay Just noticed the updated path for this renamed endpoint is using camelCase: `/bulk/{stateAbbr}/v2/uploadAllParticipants/{filename}`. We are using snake_case for the [match API](https://github.com/18F/piipan/blob/dev/docs/openapi/duplicate-participation-api.yaml#L9): `/match/v2/find_matches`.

It's a small thing, but we should probably be consistent across our APIs. Since we are already [using snake_case for the JSON bodies of the API responses](https://github.com/18F/piipan/blob/dev/docs/adr/0028-use-snake-case-for-json.md), what do you think about renaming this endpoint to also be snake_case? So, `/bulk/{stateAbbr}/v2/upload_all_participants/{filename}`.

Apologies for not catching this earlier and starting this conversation before the work was complete.

2022-04-06 16:57 UTC, ccaprio97 commented
> @ccaprio97 @bgfoshay Just noticed the updated path for this renamed endpoint is using camelCase: `/bulk/{stateAbbr}/v2/uploadAllParticipants/{filename}`. We are using snake_case for the [match API](https://github.com/18F/piipan/blob/dev/docs/openapi/duplicate-participation-api.yaml#L9): `/match/v2/find_matches`.
> 
> It's a small thing, but we should probably be consistent across our APIs. Since we are already [using snake_case for the JSON bodies of the API responses](https://github.com/18F/piipan/blob/dev/docs/adr/0028-use-snake-case-for-json.md), what do you think about renaming this endpoint to also be snake_case? So, `/bulk/{stateAbbr}/v2/upload_all_participants/{filename}`.
> 
> Apologies for not catching this earlier and starting this conversation before the work was complete.

Made the change. I assumed you only wanted it for the path and not the ref too?

2022-04-06 17:46 UTC, kingcomma commented
Yep! I'm just focusing on consistency in terms of the public-facing details like the path.

If folks are onboard with the change I suggested, I think you'll also need to update the `urlTemplate` value in `apim.json` to match the `path` update you made to the documentation/spec.

2022-04-08 19:11 UTC, merged