Updated  documentation for nac-161
18F/piipan pull request #2934
Opened 2022-04-04 17:40 UTC by kcherukupalli

## What’s changing?

Updated documentation for new `recent_benefit_issuance_dates`

## Why?
#nac-513

 
## This PR has:

- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [x ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

## Anything else?

2022-04-04 20:20 UTC, cjhskippy requested changes
I recommend one change and had a few related questions.

2022-04-04 20:20 UTC, cjhskippy commented on docs/openapi/generated/duplicate-participation-api/openapi.md
> +|»»»» recent_benefit_issuance_dates|array|false|none|List of up to the last 3 date ranges that participant received benefits, formatted as ISO 8601 time intervals (YYYY-MM-DD/YYYY-MM-DD) separated by
If this is returned as output by the NAC (which should be the case for the duplicate participation API), I believe the correct phrasing should be this one:

`List of up to the last 3 date ranges that participant received benefits, in descending order. Each date range is formatted as ISO 8601 time intervals (YYYY-MM-DD/YYYY-MM-DD) separated by spaces. This will only include the last three dates for the most recent benefits issued.`

2022-04-04 20:20 UTC, cjhskippy commented on docs/openapi/generated/duplicate-participation-api/openapi.yaml
> +                                    description: Collection of up to 3 date ranges that participant has been receiving benefits at the time the match was found.
Question: Is there a technical reason why this description differs from the description in the generated documentation?  Should this also be...

`List of up to the last 3 date ranges that participant received benefits, in descending order. Each date range is formatted as ISO 8601 time intervals (YYYY-MM-DD/YYYY-MM-DD) separated by spaces. This will only include the last three dates for the most recent benefits issued.`

2022-04-04 20:20 UTC, cjhskippy commented on docs/openapi/generated/duplicate-participation-api/openapi.yaml
> +                                      description: A single date range
Question: does this change the formatting we expect from the user?  Is the description of
`Each date range is formatted as ISO 8601 time intervals (YYYY-MM-DD/YYYY-MM-DD) separated by spaces.`
still technically accurate?

2022-04-04 20:20 UTC, cjhskippy commented on match/docs/openapi/schemas/participant-record.yaml
> +      description: "Collection of up to 3 date ranges that participant has been receiving benefits at the time the match was found."
Question: is there a technical reason why it is preferable (or worse) for us to keep this language synced with the API documentation?  Feel free to disregard if there is good reason not to use this language:
`List of up to the last 3 date ranges that participant received benefits, formatted as ISO 8601 time intervals (YYYY-MM-DD/YYYY-MM-DD) separated by spaces. Date ranges do not need to be consecutive. Fewer than 3 months can be entered for newer participants. This should only include the last three dates for the most recent benefits issued.`

2022-04-04 21:13 UTC, kcherukupalli commented on match/docs/openapi/schemas/participant-record.yaml
> +      description: "Collection of up to 3 date ranges that participant has been receiving benefits at the time the match was found."
Let me run both generate files and check it out.  I ran only generate-docs.bash.

2022-04-04 22:33 UTC, kcherukupalli commented on docs/openapi/generated/duplicate-participation-api/openapi.yaml
> +                                      description: A single date range
Given text in the ticket is more for 'import-schema.json'

2022-04-04 22:42 UTC, kcherukupalli commented on docs/openapi/generated/duplicate-participation-api/openapi.md
> +|»»»» recent_benefit_issuance_dates|array|false|none|List of up to the last 3 date ranges that participant received benefits, formatted as ISO 8601 time intervals (YYYY-MM-DD/YYYY-MM-DD) separated by
The given text is more focused on 'import-schema.json`,   updated description for the API call which will return list of Dateranges.

2022-04-04 22:50 UTC, kcherukupalli commented
Please provide the text if need to change in API calls.

2022-04-05 15:58 UTC, cjhskippy commented
These edits look like they address the questions I had.  Thank you @kcherukupalli

2022-04-05 15:59 UTC, merged