CJC-416
18F/piipan pull request #3198
Opened 2022-05-06 15:12 UTC by ccaprio97

## What’s changing?

Changing status in upload table to 'Complete' on successful upload

## Why?

NAC-416

## This PR has:

- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

## Anything else?

Unaware of any documentation to update because all affected code is internal. If some needs to be added where would that go?

2022-05-06 15:42 UTC, bgfoshay requested changes
I'm not sure this is the right approach. I think we need to move the initial record creation outside the transaction. And it should still set to "Uploading". Then we'll need a new statement, at the end of the transaction (after participants are finished being copied over) to update the upload record's status to "Complete" (or "Failed" when appropriate). Call me if you want to discuss.

2022-05-06 16:40 UTC, ccaprio97 commented
changed the original place back to 'uploading' and added new method after addParticipants. Returns the Id even though it doesnt need to. will probably need to have the id being returned when we eventually check for failed or successful plus it doesnt hurt

2022-05-06 16:47 UTC, bgfoshay commented on participants/src/Piipan.Participants/Piipan.Participants.Core/Services/ParticipantService.cs
> +                await _uploadDao.UpdateUploadStatus(upload);
Issue: I think you also need to move the following line outside/above the transaction scope.

var upload = await _uploadDao.AddUpload(uploadIdentifier);

2022-05-06 20:33 UTC, bgfoshay commented on participants/src/Piipan.Participants/Piipan.Participants.Core/Services/ParticipantService.cs
> +                await _uploadDao.UpdateUploadStatus(upload, UploadStatuses.Failed.ToString());
Thought: You should log the error here so that if one occurs, we can see what happened.

2022-05-09 18:14 UTC, bgfoshay commented on participants/src/Piipan.Participants/Piipan.Participants.Core/Services/ParticipantService.cs
> +                await _uploadDao.UpdateUploadStatus(upload, UploadStatuses.Failed.ToString());
I think it should be a simple change and if so, we should log it as part of this PR. Unless you have concerns with doing so?

2022-05-09 19:00 UTC, bgfoshay commented on participants/src/Piipan.Participants/Piipan.Participants.Core/Services/ParticipantService.cs
> +            var upload = await _uploadDao.AddUpload(uploadIdentifier);
Thought: Do we have a unit test case for upload record created but participants failed?

2022-05-09 19:03 UTC, ccaprio97 commented on participants/src/Piipan.Participants/Piipan.Participants.Core/Services/ParticipantService.cs
> +            var upload = await _uploadDao.AddUpload(uploadIdentifier);
check AfterException_AddParticipantsRollsTranactionBack

2022-05-09 19:06 UTC, bgfoshay commented on participants/tests/Piipan.Participants.Core.IntegrationTests/ParticipantServiceTests.cs
> +                    long actualLastUploadId = GetLastSuccessfulUploadId();
Thought: Aside from verifying the most recent successful uploadId, I think you should verify that the latest upload has a status = FAILED.

2022-05-09 19:18 UTC, bgfoshay commented on shared/src/Piipan.Shared.TestFixtures/ParticipantsDbFixture.cs
> +        public Int64 GetLastFailedUploadId()
Question: can you change/consolidate GetLastSuccessfulUploadId/GetLastFailedUploadId -> GetLatestUploadByStatus(string desiredStatus)?

2022-05-09 19:38 UTC, bgfoshay approved these changes
👍Thanks for addressing all of my comments!

2022-05-09 20:55 UTC, merged