Disabling match responses for certain states
18F/piipan pull request #3209
Opened 2022-05-10 16:30 UTC by dborgen2

## What’s changing?

We need a way to disable returning back matches to caller. Two possible options emerged: Put it in a configuration file, or a database table. We also needed to consider the possibility that we might want to disable it per state, instead of disabling it as a whole.

This PR shows a proof of concept of how we would do it in a configuration file. We already had the states.csv anyway, so I propose adding a third column to the CSV, which is set to TRUE if the state should be disabled from returning back matches, or FALSE if the state should process as normal. If it makes more sense to switch this around and make it an "enabled" flag instead of a "disabled" flag, we would simply negate these values.

In my opinion, the configuration file makes the most sense for a couple of reasons:

1. We already had the states.csv, so this is simply one more column on there
2. Most importantly, the speed of the check to see if we should be disabling matches would be faster, since a call to the database is a round-trip call that we would not have to make if it was in a configuration file.
3. No need to add a new table or SQL calls

It's also important to note that you can alter this on the fly in Azure by changing the configuration in the Orchestrator function, and if you do then the Azure Function will restart and pick up the new value.

The main drawback to this approach is that if it is changed in Azure and not updated in States.csv, then next time we deploy the configuration will get overridden.

If the team agrees on this approach, I'll add to the documentation and test suite

## Why?

Research for NAC-627

## This PR has:

- [x] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [x] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

## Anything else?

2022-05-16 17:33 UTC, bgfoshay commented on match/src/Piipan.Match/Piipan.Match.Func.Api/Api.cs
> +                string disabledMatchingStates = Environment.GetEnvironmentVariable("StatesToDisableMatches");
Thought: Should we consider moving this out of the Find call? Or caching it (after reading it the first time) so that we don't need to parse it with every call to Find?

2022-05-16 18:34 UTC, bgfoshay commented on match/src/Piipan.Match/Piipan.Match.Func.Api/Api.cs
> +                if (disabledStates.Contains(initiatingState.ToLower()))
Question: Should we consider an additional condition that the matching state is also not in disabledStates? e.g. the initiating state is enabled, but a match is found with a state that is disabled?

2022-05-16 18:50 UTC, dborgen2 commented on match/src/Piipan.Match/Piipan.Match.Func.Api/Api.cs
> +                if (disabledStates.Contains(initiatingState.ToLower()))
Yea, that's definitely a valid question. I'll ask Andrew, and if he says we should do that I'll make sure to implement it when creating the final PR

2022-05-16 19:05 UTC, dborgen2 commented on match/src/Piipan.Match/Piipan.Match.Func.Api/Api.cs
> +                string disabledMatchingStates = Environment.GetEnvironmentVariable("StatesToDisableMatches");
From what I'm seeing, a new MatchApi instance is created every time the function is called, so moving it to the constructor wouldn't really be of any benefit, and in fact may potentially hurt response time if we ever have another function in the file that doesn't depend on this environment variable.

That being said, it should speed it up a bit to use a MemoryCache singleton, so I believe the final implementation should utilize that.

2022-05-16 19:38 UTC, bgfoshay commented on match/src/Piipan.Match/Piipan.Match.Func.Api/Api.cs
> +                if (disabledStates.Contains(initiatingState.ToLower()))
👍

2022-05-23 20:22 UTC, cjhskippy requested changes

2022-05-23 20:25 UTC, dborgen2 commented on iac/arm-templates/function-orch-match.json
> +        "statesToDisableMatches": {
Yep, not a problem. I was wondering about that.. I'll reverse it

2022-05-23 20:32 UTC, dborgen2 commented on iac/states.csv
> +IA,Iowa,FALSE
Currently no, but I think this would be a great idea. I can add that in the final code

2022-05-30 16:58 UTC, dborgen2 commented on match/src/Piipan.Match/Piipan.Match.Func.Api/Api.cs
> +                string disabledMatchingStates = Environment.GetEnvironmentVariable("StatesToDisableMatches");
Added MemoryCache

2022-05-30 16:59 UTC, dborgen2 commented on iac/states.csv
> +IA,Iowa,FALSE
FYI, after talking with Ryan there's nothing to do for this PR. He said they will maintain separate states.csv files depending on where they are publishing. So the result is the same, just nothing needing to be updated for this PR.

2022-05-30 20:11 UTC, bgfoshay commented on match/src/Piipan.Match/Piipan.Match.Func.Api/Api.cs
> +                    string enabledStates = Environment.GetEnvironmentVariable("EnabledStates");
Question: Should you convert to lowercase for consistent comparison purposes?

2022-05-30 20:16 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.Api.IntegrationTests/ApiIntegrationTests.cs
> +            Environment.SetEnvironmentVariable("EnabledStates", "ea,eb");
Thought: Might be good to test with various capitalization. But I haven't finished review so you might have this elsewhere.

2022-05-30 20:19 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.Api.IntegrationTests/ApiIntegrationTests.cs
> +            Assert.Empty(resultObject.Data.Results[0].Matches);
Question: Do we need to verify that a match record was still created, even though an empty response was provided.

2022-05-30 20:35 UTC, dborgen2 commented on match/tests/Piipan.Match.Func.Api.IntegrationTests/ApiIntegrationTests.cs
> +            Assert.Empty(resultObject.Data.Results[0].Matches);
Good idea. Just added an assert for that

2022-05-30 20:36 UTC, dborgen2 commented on match/src/Piipan.Match/Piipan.Match.Func.Api/Api.cs
> +                    string enabledStates = Environment.GetEnvironmentVariable("EnabledStates");
Good idea. It was lowercasing in create-resources.bash, but in case they edited it directly in Azure we should lowercase it.

2022-05-30 20:43 UTC, bgfoshay approved these changes
👍

2022-05-30 20:52 UTC, merged