Adding match status Tag to the Match ID header on the Match Detail page
18F/piipan pull request #3299
Opened 2022-06-01 14:58 UTC by dborgen2

## What’s changing?

We want to show the Match Status, either Open or Closed, in a tag next to the Match ID. To accomplish this, first a Tag component was created in the Components library, and then brought in to the Match Detail page. The tag was also added to the components library demo project, so you can visualize it in different themes/borders easily on there.

## Why?

Closes NAC-166

## This PR has:

- [x] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [x] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

## Anything else?

2022-06-10 14:12 UTC, bgfoshay commented on match/src/Piipan.Match/Piipan.Match.Api/Models/StateInfoResponseData.cs
> +    public class StateInfoResponseData
Question: Does this class align with the StateInfo work Conner's been working? Should we consider having this response defined in the new StateInfo libraries he's created? Or reusing one of the classes he's defined there?

2022-06-10 14:16 UTC, dborgen2 commented on match/src/Piipan.Match/Piipan.Match.Api/Models/StateInfoResponseData.cs
> +    public class StateInfoResponseData
Actually, these ones are a mistake from back when I thought we were just adding it to the Match API. I thought I got rid of them but apparently I did not. You'll notice identical classes at the bottom of this PR, which are the same as Conner's and I'm working to merge the two together

2022-06-10 15:52 UTC, bgfoshay requested changes
You covered a lot of ground here! Overall looks pretty good. Some minor questions & comments. Biggest issue was the overlap with Conner's StateInfo implementation which I believe you're already working to address.

2022-06-10 15:52 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/GetMatchApiIntegrationTests.cs
> +            Assert.Null(resBody.Data.Dispositions[0].InvalidMatch);
Nitpick: Is this check explicit enough? Potentially resBody or Data or Dispositions could be null as well.

2022-06-10 15:52 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/GetMatchesApiIntegrationTests.cs
> +            Assert.Null(resBody.Data.First().Dispositions[0].InvalidMatch);
Nitpick: Same as earlier comment regarding whether this null check is explicit enough.

2022-06-10 15:52 UTC, bgfoshay commented on query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/MatchDetail.razor
> +        Match.Data.Data.States.FirstOrDefault(s => string.Compare(s, Match.Data.Data.Initiator, StringComparison.CurrentCultureIgnoreCase) != 0);
Question: Isn't this retrieving the initiating state abbreviation?

2022-06-10 15:56 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/GetMatchApiIntegrationTests.cs
> +            Assert.Null(resBody.Data.Dispositions[0].InvalidMatch);
👍

2022-06-10 15:56 UTC, dborgen2 commented on query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/MatchDetail.razor
> +        Match.Data.Data.States.FirstOrDefault(s => string.Compare(s, Match.Data.Data.Initiator, StringComparison.CurrentCultureIgnoreCase) != 0);
Eh... it technically works since I'm checking != 0, but it should be switched to MatchingStateAbbreviation for consistency. Good catch

2022-06-10 15:56 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/GetMatchesApiIntegrationTests.cs
> +            Assert.Null(resBody.Data.First().Dispositions[0].InvalidMatch);
👍 Saw your response above.

2022-06-13 18:48 UTC, dborgen2 commented on match/src/Piipan.Match/Piipan.Match.Core/Builders/MatchResAggregator.cs
> +                // Grab the vulnerable individual status from the original match if it hasn't been updated by an event
Moved this logic to MergeEvents. Good suggestion

2022-06-13 18:49 UTC, dborgen2 commented on query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/MatchDetail.razor
> +        Match.Data.Data.States.FirstOrDefault(s => string.Compare(s, Match.Data.Data.Initiator, StringComparison.CurrentCultureIgnoreCase) != 0);
Actually no, sorry I read too fast. This is the property to determine the matching state abbreviation. This should be equal to the state abbreviation that is not the initiating state, so this logic is correct.

2022-06-13 18:49 UTC, dborgen2 commented on states/src/Piipan.States.Api/Piipan.States.Api.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Projects merged

2022-06-13 19:01 UTC, dborgen2 commented on query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/StateParticipantInformation.razor
> +        StateValues.Add(new("Participant Closing Date", InitiatingState ? "N/A" : Participant.ParticipantClosingDate));
Added comments for clarification

2022-06-13 19:59 UTC, bgfoshay commented on query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/StateParticipantInformation.razor
> +        StateValues.Add(new("Participant Closing Date", InitiatingState ? "N/A" : Participant.ParticipantClosingDate));
👍

2022-06-13 20:01 UTC, bgfoshay commented on query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/MatchDetail.razor
> -                    <ul>
Question: Did you mean to pull out these details from the page?

2022-06-13 20:03 UTC, dborgen2 commented on query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/MatchDetail.razor
> -                    <ul>
Yea, Corey removed it from his design. I don't remember the exact reason, but he said it could be removed.

2022-06-13 20:10 UTC, ryangeorgeharvey commented on iac/create-resources.bash
> +    --name match-res-api \
Suggestion: Change naming to state

2022-06-13 20:14 UTC, dborgen2 commented on iac/create-resources.bash
> +    --name match-res-api \
Yea, good call. Missed that one

2022-06-13 20:23 UTC, bgfoshay approved these changes
LGTM. Thanks for addressing my comments and coordinating with Conner's work!

2022-06-13 20:26 UTC, bgfoshay requested changes
Actually, just noticed the drop in coverage so I guess we need to address that first.

2022-06-13 20:30 UTC, bgfoshay commented on query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/MatchDetail.razor
> -                    <ul>
👍

2022-06-14 01:32 UTC, bgfoshay approved these changes
👍

2022-06-14 01:39 UTC, merged