Adding Notifications Project to add email functionality
18F/piipan pull request #3337
Opened 2022-06-10 21:01 UTC by ccaprio97

## What’s changing?

Made new shared notifications project and test project to send emails with smtp server

## Why?

NAC-769

## This PR has:

- [X] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [X] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

## Anything else?

2022-06-10 23:39 UTC, bgfoshay requested changes
Looks like a good start for notification support! Couple changes we still need though- you should additionally add the new projects to the shared.sln solution file. Also, the tests should be added to the circleci coverage and we need dependabot to cover these solutions as well.

2022-06-13 16:13 UTC, ccaprio97 commented on system.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Piipan.Shared.Notifications", "shared\src\Piipan.Shared.Notifications\Piipan.Shared.Notifications.csproj", "{04D97589-4A30-4225-AE0F-455E53AE6337}
@bgfoshay  the new projects are in the system solution. Do you mean something else?

2022-06-13 16:34 UTC, bgfoshay commented on system.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Piipan.Shared.Notifications", "shared\src\Piipan.Shared.Notifications\Piipan.Shared.Notifications.csproj", "{04D97589-4A30-4225-AE0F-455E53AE6337}
In the shared folder, there is a shared.sln file. We should make sure to add the projects there as well.

2022-06-13 18:32 UTC, bgfoshay approved these changes
👍

2022-06-13 18:33 UTC, merged