Nac 1116 email queue client
18F/piipan pull request #3682
Opened 2022-08-22 18:14 UTC by kcherukupalli

## What’s changing?
Emails can be customized based  type of the request template.  Hardcoded templates will be replaced in future sprint based on the requirements.
Still need to get the Mail client details to complete the Notifications.

## Why?
@nac-1116
_Link to specific issue (ex: Closes #123)_

## This PR has:

- [ x] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [ x] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [ x] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

## Anything else?
   Currently we are just logging the email content in Azure function.
   Hardcoded test email templates and will customize in the future sprints based on the requirement.
   All the documentation will be updated once we finish the Notifications.

2022-08-22 19:41 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Core/Services/INotificationPublish.cs
> +        Task PublishEmail(EmailModel metrics);
Nitpick: Should we consider another name rather than 'metrics'?

2022-08-22 19:42 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Core/Services/NotificationPublish.cs
> +        public Task PublishEmail(EmailModel metrics)
Nitpick: Same question as before, should this parameter be named differently?

2022-08-22 19:43 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Core/Services/NotificationPublish.cs
> +                //We want to use pre-serialized verion of the ParticipantMatch.
Nitpick/Question: Should these comments be more generic rather than referring to ParticipantMatch?

2022-08-22 19:46 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Core/Services/NotificationService.cs
> +        public async Task<bool> CreateMessageFromTemplate(EmailTemplateInput emailTemplateInput)
Question: Is this method publishing a message to the queue? If so, should we indicate that action in the method name?

2022-08-22 19:47 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Core/Services/NotificationService.cs
> +        public async Task<bool> MessageFromTemplate(string topic, object templateData,
Question: Is this method publishing a message to the queue? If so, should we indicate that action in the method name?

2022-08-22 19:50 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Core/Services/NotificationService.cs
> +            if (topic == "UPDATE_MATCH_RES")
Question: Currently this file seems coupled to matches? Will this approach potentially result in a large if/else section for every potential topic that needs a notification?

2022-08-22 19:52 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Func.Api/Api.cs
> +        [FunctionName("PublishEmail")]
Nitpick: Is there anything to stop this design from using text notifications, or even push notifications, in the future? i.e. is it tied to email?

2022-08-22 20:16 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Core.Integration.Tests/NotificationPublishTest.cs
> +            //  notificationService.Verify(m => m.CreateMessageFromTemplate(It.IsAny<EmailTemplateInput>()), Times.Once);
Question: Can you not verify this was called? Is there a relationship between INotificationService and NotificationApi?

2022-08-22 20:16 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Core.Integration.Tests/NotificationPublishTest.cs
> +            // Assert
Question: same question as above

2022-08-22 20:22 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Client/NotificationClient.cs
> +        public Task<bool> CreateMessageFromTemplate(EmailTemplateInput emailTemplateInput)
Question: Should we consider renaming this something like "PublishMessageFromTemplate"?

2022-08-22 20:24 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Core.Integration.Tests/NotificationPublishTest.cs
> +    public class NotificationPublishTest
Question: This class seems like it's geared towards testing NotificationApi.cs rather than NotificationPublish.cs?

2022-08-22 20:28 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Core.Tests/Models/EmailModelTest.cs
> +        public void Equals_OverrideTests()
Question: I'm not sure I follow what this test is looking to verify?

2022-08-22 20:30 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Core.Tests/Services/EmailServiceTests.cs
> +    public class EmailServiceTests
Question: are these tests actually going to send an email?

2022-08-22 20:34 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Core.Tests/Services/NotificationPublishTest.cs
> +            publisherClientMock.Verify(x => x.SendEventAsync(It.Is<EventGridEvent>(s => s.EventType == "Publish to the queue"), default));
Question: will this be called if the environment variables aren't set? Should there be some setup here on a mock that throws an exception?

2022-08-22 20:36 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Core.Tests/Services/NotificationServiceTest.cs
> +    public class NotificationServiceTest
Question: Would there be any benefit to tests where NoticationPublish.PublishEmail throws an exception or the class is null?

2022-08-22 20:38 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Func.Api.Integration.Tests/NotificationTests.cs
> +            var notificationService = new Mock<INotificationService>();
Question: Can we remove this variable?

2022-08-22 20:44 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Func.Api.Tests/Program.cs
> +Console.WriteLine("Hello, World!");
Question: Looks like default sample code got left in?

2022-08-22 20:57 UTC, kcherukupalli commented on Notifications/src/Piipan.Notifications.Core/Services/NotificationService.cs
> +            if (topic == "UPDATE_MATCH_RES")
This would be  refactored based the requirements for different email types/topics.  One option is to store email templates in DB and have an identifier to retrieve the template.

2022-08-22 20:59 UTC, bgfoshay commented on iac/arm-templates/function-notifications.json
> +                        // Bind backing services
Question: Is the app querying/using the collaboration database?

2022-08-22 21:03 UTC, bgfoshay commented on iac/create-resources.bash
> +      --included-event-types Microsoft.Storage.BlobCreated \
Question: Is BlobCreated the correct event type?

2022-08-22 21:04 UTC, bgfoshay commented on iac/iac-common.bash
> +#Search Metric Event grid
Nitpick: comment refers to "Metric Event grid"?

2022-08-22 21:07 UTC, bgfoshay commented on match/src/Piipan.Match/Piipan.Match.Core/Services/MatchEventService.cs
> +                    TemplateData = new
Question: Wasn't this object already created on line 153 above?

2022-08-22 21:09 UTC, bgfoshay commented on match/src/Piipan.Match/Piipan.Match.Core/Services/MatchEventService.cs
> +                await _notificationService.CreateMessageFromTemplate(emailTemplateInput);
Question: Is this method supposed to get called twice?

2022-08-22 21:10 UTC, kcherukupalli commented on match/src/Piipan.Match/Piipan.Match.Core/Services/MatchEventService.cs
> +                await _notificationService.CreateMessageFromTemplate(emailTemplateInput);
Yes, For Initiating state and Matching state.

2022-08-22 21:11 UTC, kcherukupalli commented on match/src/Piipan.Match/Piipan.Match.Core/Services/MatchEventService.cs
> +                await _notificationService.CreateMessageFromTemplate(emailTemplateInput);
Since Content of the email will be different for both states.

2022-08-22 21:16 UTC, bgfoshay commented on match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/AddEventApi.cs
> +                //Send Notification to both initiating state and Matching State.
Question: Aside from the topic name, this logic looks very similar to the logic in MatchEventService. Is there any opportunity to consolidate/encapsulate this logic in a separate class?

2022-08-22 21:18 UTC, kcherukupalli commented on Notifications/tests/Piipan.Notifications.Core.Integration.Tests/NotificationPublishTest.cs
> +            //  notificationService.Verify(m => m.CreateMessageFromTemplate(It.IsAny<EmailTemplateInput>()), Times.Once);
NotificationService  will  Transform the email and then publish it to the Queue.  NotificationApi will pick it from there and process it.

2022-08-22 21:19 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Core/Services/NotificationService.cs
> +            Template subjectTemplateMS = new Template(g, emailSubjectMS);
Question: Is this being used?

2022-08-22 21:21 UTC, bgfoshay commented on match/tests/Piipan.Match.Core.Tests/Services/MatchEventServiceTests.cs
> +            notificationService.Verify(r => r.CreateMessageFromTemplate(It.Is<EmailTemplateInput>(p => p.Topic == topic)), Times.Exactly(2));
Question: Should you also verify the initiating state, matching state, and EmailTo values?

2022-08-22 21:22 UTC, bgfoshay commented on match/tests/Piipan.Match.Core.Tests/Services/MatchEventServiceTests.cs
> +            notificationService.Verify(r => r.CreateMessageFromTemplate(It.Is<EmailTemplateInput>(p => p.Topic == topic)), Times.Never);
Question: Should you also verify the initiating state, matching state, and EmailTo values?

2022-08-22 21:24 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/AddEventIntegrationTests.cs
> +            ClearMatchRecords();
Question: Does the order of these calls matter? If so, maybe it would be helpful to add a comment

2022-08-22 21:26 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.ResolutionApi.Tests/AddEventApiTests.cs
> +            notificationService.Verify(r => r.CreateMessageFromTemplate(It.Is<EmailTemplateInput>(p => p.Topic == topic)), Times.Never());
Question: Should you also verify the initiating state, matching state, and EmailTo values?

2022-08-22 21:26 UTC, bgfoshay commented on match/tests/Piipan.Match.Func.ResolutionApi.Tests/AddEventApiTests.cs
> +            notificationService.Verify(r => r.CreateMessageFromTemplate(It.Is<EmailTemplateInput>(p => p.Topic == topic)), Times.Never());
Question: Should you also verify the initiating state, matching state, and EmailTo values?

2022-08-22 21:30 UTC, bgfoshay requested changes
I know I had a lot of questions/comments but this is a lot of great work! You turned this around quickly. 

I think my biggest question revolves around the use/intention of NotificationService and how it will expand in the future to other notification types outside of matches. Other than that, I think most of my comments were minor.

2022-08-22 21:36 UTC, bgfoshay commented on Notifications/src/Piipan.Notifications.Func.Api/Api.cs
> +        [FunctionName("PublishEmail")]
Question: Thinking about this more, I'm wondering if the name of this function will be clear to future developers reviewing the code. The Function sends an email, so in that sense, it's publishing. But it's "subscribing" to notification requests in the "emailbucket" queue. I know it's wordy, but maybe the function should be named something like "NotificationRequestProcessor"?

2022-08-22 21:38 UTC, kcherukupalli commented on Notifications/src/Piipan.Notifications.Func.Api/Api.cs
> +        [FunctionName("PublishEmail")]
Sure, will rename it to "NotificationRequestProcessor"

2022-08-22 21:40 UTC, bgfoshay commented on Notifications/tests/Piipan.Notifications.Core.Integration.Tests/NotificationPublishTest.cs
> +            //  notificationService.Verify(m => m.CreateMessageFromTemplate(It.IsAny<EmailTemplateInput>()), Times.Once);
So there's no direct relationship between the two classes, right? NotificationClient implements INotificationApi and it acts as a subscriber to the queue? But NotificationService can be removed here, right?

2022-08-22 23:08 UTC, kcherukupalli commented on Notifications/src/Piipan.Notifications.Func.Api/Api.cs
> +        [FunctionName("PublishEmail")]
We might need to customize the functions based on notification types.

2022-08-22 23:22 UTC, kcherukupalli commented on Notifications/tests/Piipan.Notifications.Core.Integration.Tests/NotificationPublishTest.cs
> +            //  notificationService.Verify(m => m.CreateMessageFromTemplate(It.IsAny<EmailTemplateInput>()), Times.Once);
Renamed the file to NotificationApiTest and removed NotificationServices.

2022-08-22 23:22 UTC, kcherukupalli commented on Notifications/tests/Piipan.Notifications.Core.Integration.Tests/NotificationPublishTest.cs
> +            // Assert
Renamed the file to NotificationApiTest and removed NotificationServices.

2022-08-22 23:27 UTC, kcherukupalli commented on Notifications/tests/Piipan.Notifications.Core.Tests/Services/NotificationPublishTest.cs
> +            publisherClientMock.Verify(x => x.SendEventAsync(It.Is<EventGridEvent>(s => s.EventType == "Publish to the queue"), default));
Emails are not sent out yet, removed EmailService from the project file.  We will implement after getting the decision on email provider.

2022-08-23 00:58 UTC, kcherukupalli commented on match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/AddEventApi.cs
> +                //Send Notification to both initiating state and Matching State.
Logic would be different for new email templates based on the requirements.  In future we might end up consolidating the logic .

2022-08-23 01:17 UTC, kcherukupalli commented on match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/AddEventIntegrationTests.cs
> +            ClearMatchRecords();
In pipeline there won't be but when we try in dev there is an issue with referential integrity.

2022-08-23 02:55 UTC, kcherukupalli commented on match/tests/Piipan.Match.Core.Tests/Services/MatchEventServiceTests.cs
> +            notificationService.Verify(r => r.CreateMessageFromTemplate(It.Is<EmailTemplateInput>(p => p.Topic == topic)), Times.Never);
Comparing with Topic and EmailTo.

2022-08-23 02:57 UTC, kcherukupalli commented on match/tests/Piipan.Match.Func.ResolutionApi.Tests/AddEventApiTests.cs
> +            notificationService.Verify(r => r.CreateMessageFromTemplate(It.Is<EmailTemplateInput>(p => p.Topic == topic)), Times.Never());
Comparing with Topic and EmailTo.  For "Never"  only comparing with Topic.

2022-08-23 02:57 UTC, kcherukupalli commented on match/tests/Piipan.Match.Func.ResolutionApi.Tests/AddEventApiTests.cs
> +            notificationService.Verify(r => r.CreateMessageFromTemplate(It.Is<EmailTemplateInput>(p => p.Topic == topic)), Times.Never());
Comparing with Topic and EmailTo.  For "Never"  only comparing with Topic.

2022-08-23 13:35 UTC, kcherukupalli commented on Notifications/tests/Piipan.Notifications.Core.Tests/Services/EmailServiceTests.cs
> +    public class EmailServiceTests
Still EmailService is not part of this story.

2022-08-23 13:35 UTC, kcherukupalli commented on iac/create-resources.bash
> +      --included-event-types Microsoft.Storage.BlobCreated \
Changed the Event Grid type.

2022-08-25 04:11 UTC, closed without merging