Fixing Get Upload By Id Arm Template Bug
18F/piipan pull request #3943
Opened 2022-10-07 21:07 UTC by ccaprio97

## What’s changing?

updating arm template to have each states app id

## Why?

NAC-1411

## This PR has:

- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [x] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

## Anything else?

2022-10-07 21:12 UTC, ccaprio97 commented
forgot to remove all the echo statements and put the workplace id back into create apim bash. will do

2022-10-10 14:28 UTC, bgfoshay commented on iac/create-apim.bash
> +  echo "HERE IS THE ORCH ID!!!!!!"
Nitpick: Did you mean to leave these echo statements in here?

2022-10-10 14:28 UTC, bgfoshay commented on iac/create-apim.bash
> +  #echo "HERE IS THE EA ETL APP ID!!!!!!!!!!!!!!!!!!!!!!!!!"
Nitpick: commented out debugging code?

2022-10-10 14:30 UTC, bgfoshay commented on iac/create-apim.bash
> -        workspaceId="${LOG_ANALYTICS_WORKSPACE_ID}" \
Question: Was the removal of this parameter intentional?

2022-10-10 14:31 UTC, bgfoshay requested changes
The approach looks good. The comments and debug statements could use some cleaning up. And there's one section that's hardcoded to your resources that needs to be fixed. But overall, good job figuring out a way to do the replacements.

2022-10-14 19:39 UTC, ryangeorgeharvey commented on iac/arm-templates/apim-bulkupload.json
> +        },
nitpick (non-blocking): Add a description for the ARM variable.

2022-10-14 19:45 UTC, ryangeorgeharvey commented on iac/create-apim.bash
> +      state_app_id_list+=("${single_state_etl_app_id}")
nitpick (non-blocking): line 151 is indented too much. It should be aligned with line 145.

2022-10-14 19:49 UTC, ryangeorgeharvey approved these changes
Changes LGTM, but recommend making the minor fixes.

2022-10-14 19:55 UTC, bgfoshay approved these changes
👍

2022-10-17 15:33 UTC, merged